### ISSUE TITLE
Define and document project goal and scope

### ISSUE THREAD

**Issue by RancyKaur** [RancyKaur/SOEN6841_Project#5]

**Comment by harika89** [comment]
Project Goal:
The goal of this project is to develop and launch an advanced language learning chatbot that incorporates conversational AI and a Custom Scenario Creator to boost language proficiency among young adults and university students. This chatbot will provide an engaging and personalized learning experience, offering interactive conversations, quizzes, real-time feedback, and user-generated scenarios tailored to the learners' interests and goals.

Project Scope:
The project's scope includes developing an intelligent chatbot for language learning that is targeted toward young adults, college students and incorporates conversational AI features along with a Custom Scenario Creator. This includes developing an AI-powered chatbot that can have interactive conversations with users and interpret natural language inputs in coupled with integrating a feature that lets users create personalized learning scenarios. The project also involves creating a user-friendly interface, a variety of language-learning personalized paths, implementing real-time feedback mechanisms.
